### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Badsauce/basic-rails-app#1]
:+1: Nice use of SCSS and `flex`! Since flexbox support is still pretty spotty, you might find [the `autoprefixer-rails` gem](https://github.com/ai/autoprefixer-rails) interesting. It will take something like:

``` css
.nav {
  display: flex;
}
```

and automatically build it out to something like the below during compilation, for maximum browser support:

``` css
.nav {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
}
```
